### PR TITLE
Wrapping new lines fix

### PR DESCRIPTION
**Pull request by SpeckyYT**
I'm having the following problem:
image
by adding a -1 to the columns count, it will get fixed.

### CODE REVIEW

**Comment by sindresorhus** [comment]
What OS and terminal?

**Comment by SpeckyYT** [comment]
Windows 7 with cmd.exe terminal.
Maybe there should be an option or something for it...

**Comment by sindresorhus** [comment]
At least guard this change behind a Windows check. And a code comment.

**Comment by SpeckyYT** [comment]
Sorry for being a newbie at working with other people, but I don't understand what you mean with `guard this change behind a Windows check`.

**Comment by SpeckyYT** [comment]
I'm not sure if this fix works for for other terminals, but it works like intended on Windows 7.

**Comment by sindresorhus** [comment]
This will be fixed as a part of https://github.com/sindresorhus/terminal-image/pull/23.

**Pull request closed without merging**
